# Generated by Django 4.2.6 on 2023-10-28 10:26

import accountapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=128, null=True)),
                ('firstname', models.CharField(max_length=128, null=True)),
                ('middlename', models.CharField(max_length=128, null=True)),
                ('nmn', models.BooleanField(default=False, null=True)),
                ('ext_phone', models.CharField(max_length=128, null=True)),
                ('ser_phone', models.CharField(max_length=128, null=True)),
                ('pri_phone', models.CharField(max_length=128, null=True)),
                ('avatar', models.ImageField(null=True, upload_to=accountapp.models.get_profile_avatar_filepath)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
