"""
Django settings for spsm project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',

    'homeapp',

    'aboutapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spsm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spsm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": True,
#     "formatters": {
#         "debug_formatter": {
#             "format": "[{levelname}]: [{asctime}] [{module}] {message}",
#             "datefmt": "%d.%m.%Y %H:%M:%S",
#             "style": "{",
#         },
#         "common_formatter": {
#             "format": "[{levelname}] [{ascname}] [msg:{message}]",
#             "datefmt": "%d.%m.%Y %H:%M:%S",
#             "style": "{",
#         },
#     },
#
#     "handlers": {
#         "debug_handler": {
#             "level": "DEBUG",
#             "class": "logging.StreamHandler",
#             "formatter": "debug_formatter",
#         },
#         "info_handler": {
#             "level": "INFO",
#             "class": "logging.handlers.RotatingFileHandler",
#             "backupCount": 10,
#             "formatter": "common_formatter",
#             "filename": "logs/info.log",
#             "maxBytes": 1048576,
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["debug_handler"],
#             "level": "DEBUG",
#             "propagate": False,
#         },
#         "info_logger": {
#             "handlers": ["info_handler"],
#             "level": "INFO",
#             "propagate": False,
#         },
#     },
# }
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "debug_formatter": {
            "format": "[{levelname} {asctime} {module} %(funcName)s] %(username)s [{message}]",
            "datefmt": "%d.%m.%Y в %H:%M:%S",
            "style": "{",
        },
        "common_formatter": {
            "format": "[{levelname}] | [{asctime}] | [{module}] | [{message}]",
            "datefmt": "%d.%m.%Y в %H:%M:%S",
            "style": "{",
        },
    },

    "handlers": {
        "debug_handler": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "debug_formatter",
        },
        "info_handler": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "logs/info.log",
            "formatter": "common_formatter",
        },
        "error_handler": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": "logs/errors.log",
            "formatter": "debug_formatter",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["debug_handler", "info_handler", "error_handler"],
            "level": "DEBUG",
        },
    }
}