# Generated by Django 4.2.6 on 2023-12-01 06:37

from django.db import migrations, models
import profileapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to=profileapp.models.get_avatar_file_path)),
            ],
            options={
                'db_table': 'avatars',
            },
        ),
    ]
