# Generated by Django 4.2.6 on 2023-10-12 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profileapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('middlename', models.CharField(blank=True, max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=128, null=True)),
                ('departmnent', models.CharField(max_length=128, null=True)),
                ('extphone', models.CharField(blank=True, max_length=128)),
                ('priphone', models.CharField(blank=True, max_length=128)),
                ('serphone', models.CharField(blank=True, max_length=128)),
                ('photo', models.ImageField(null=True, upload_to=profileapp.models.get_user_photo_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
