# Generated by Django 4.2.6 on 2024-03-22 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_alter_job_options'),
        ('departments', '0002_alter_department_options_alter_department_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=128)),
                ('firstname', models.CharField(max_length=128)),
                ('middlename', models.CharField(blank=True, max_length=128)),
                ('nmn', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('dept', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='department', to='departments.department')),
                ('job', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='job_title', to='jobs.job')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
