# Generated by Django 4.2.6 on 2023-10-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nmn',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
