# Generated by Django 4.2.6 on 2023-12-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=128)),
                ('num', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
    ]
