# Generated by Django 4.2.9 on 2024-01-04 18:03

from django.db import migrations, models
import django.db.models.deletion
import profileapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=profileapp.models.get_avatar_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='profileapp.profile')),
            ],
            options={
                'db_table': 'avatars',
            },
        ),
    ]
