# Generated by Django 4.2.6 on 2024-03-28 04:49

from django.db import migrations, models
import django.db.models.deletion
import profileapp.models.model_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_dept_alter_profile_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=profileapp.models.model_avatar.get_avatar_file_path)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='profileapp.profile')),
            ],
            options={
                'db_table': 'avatars',
            },
        ),
    ]
