# Generated by Django 4.2.6 on 2023-12-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='image',
        ),
    ]
