# Generated by Django 4.2.6 on 2023-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_rename_avatar_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=128)),
                ('addr', models.EmailField(max_length=128)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
    ]
