# Generated by Django 4.2.6 on 2023-12-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='desc',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='num',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
