# Generated by Django 4.2.6 on 2023-12-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_phone_desc_alter_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='addr',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='desc',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
