# Generated by Django 4.2.6 on 2023-12-02 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0006_alter_email_addr_alter_email_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=128, null=True)),
                ('firstname', models.CharField(max_length=128, null=True)),
                ('middlename', models.CharField(max_length=128, null=True)),
                ('nmn', models.BooleanField(default=False)),
                ('work_mail', models.EmailField(max_length=128, null=True)),
                ('ext_phone', models.CharField(max_length=128, null=True)),
                ('work_phone', models.CharField(max_length=128, null=True)),
                ('self_phone', models.CharField(max_length=128, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
