# Generated by Django 4.2.6 on 2023-12-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='profileapp.profile'),
        ),
    ]
