# Generated by Django 4.2.8 on 2023-12-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_alter_profile_ext_phone_alter_profile_self_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ext_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Внут. тел.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middlename',
            field=models.CharField(max_length=128, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Лич. тел.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_mail',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='Раб. почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Служ. тел.'),
        ),
    ]
